# Generated by Django 6.0.2 on 2026-03-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_images',
            field=models.ImageField(blank=True, upload_to='photos/products/variations'),
        ),
    ]
