# Generated by Django 6.0.2 on 2026-03-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation_variation_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_images',
        ),
    ]
